a51-vendor: Add missing hardware/samsung
error: vendor/samsung/a51/Android.bp:139:1: "libbauthtzcommon" depends on undefined module "libteecl".

Signed-off-by: FelcoX <parbindarsingh@outlook.com>